spring:
  application:
    name: eureka-server

#Tomcat Embedded Server Configuration
server:
  port: 8083

#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka
